"""
Django settings for scholarscan project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-7-1plie*qp7=shv6e18#rnx95&9qtbdl!@r)_ti35=q2=t94mm"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "qr-base-attendance-afnhs.onrender.com"]

#ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "crispy_forms",
    "crispy_tailwind",
    # Local apps
    "attendance",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware", #render
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "scholarscan.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "attendance.context_processors.school_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "scholarscan.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    #"default": {
   #     "ENGINE": "django.db.backends.postgresql",
   #     "NAME": os.getenv("DB_NAME", "scholarscan_db"),
   #     "USER": os.getenv("DB_USER", "postgres"),
   #     "PASSWORD": os.getenv("DB_PASSWORD", "admin12345"),
   #     "HOST": os.getenv("DB_HOST", "localhost"),
   #     "PORT": os.getenv("DB_PORT", "5432"),
   # }

     #Render Deployment
    # 'default': {
    #    'ENGINE': 'django.db.backends.postgresql',
    #    'NAME': 'scholarscan_db',
    #    'USER': 'scholarscan_db_user',
    #    'PASSWORD': 'R09qXl7VtFYRdIm1YeuEbSCWHo4BETxG',
    #    'HOST': 'dpg-d58tfc8gjchc73ac9e2g-a',
    #    'PORT': '5432',
    #}

     # Using Render's DATABASE_URL environment variable
    'default':{
       'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'scholarscan_db',  # database name
        'USER': 'scholarscan_db_user',  # username
        'PASSWORD': 'R09qXl7VtFYRdIm1YeuEbSCWHo4BETxG',  # password
        'HOST': 'dpg-d58tfc8gjchc73ac9e2g-a.oregon-postgres.render.com',  # host
        'PORT': '5432',  # default PostgreSQL port
    } 
    # postgresql://scholarscan_db_user:R09qXl7VtFYRdIm1YeuEbSCWHo4BETxG@dpg-d58tfc8gjchc73ac9e2g-a.oregon-postgres.render.com/scholarscan_db
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Manila"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (uploads)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Crispy Forms Configuration
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

# Custom User Model
AUTH_USER_MODEL = "attendance.User"

# Login/Logout URLs
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

JAZZMIN_SETTINGS = {
    "site_title": "ScholaScan Admin",
    "site_header": "ScholarScan",
    "site_brand": "ScholarScan",
    "welcome_sign": "Welcome to ScholarScan Admin",
    "site_logo": "afnhs123.png",
    "copyright": "ArSystems",
}
