# Generated by Django 5.0.1 on 2025-12-28 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='ScholarScan Academy', max_length=200)),
                ('absence_alert_threshold', models.IntegerField(default=3, help_text='Number of absences before triggering a warning notification')),
                ('enable_auto_sms', models.BooleanField(default=True, help_text='Automatically trigger notifications for every absence')),
                ('scan_tolerance_minutes', models.IntegerField(default=15, help_text='Minutes before/after class to allow scanning')),
            ],
            options={
                'verbose_name': 'School Setting',
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisory_grade', models.IntegerField(blank=True, choices=[(7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')], help_text='Grade level of the advisory class', null=True)),
                ('advisory_section', models.CharField(blank=True, help_text='Section name of the advisory class', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profiles',
                'db_table': 'teacher_profiles',
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time_in_am', models.TimeField(blank=True, null=True)),
                ('time_out_am', models.TimeField(blank=True, null=True)),
                ('time_in_pm', models.TimeField(blank=True, null=True)),
                ('time_out_pm', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day')], default='PRESENT', max_length=20)),
                ('minutes_late', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to='attendance.studentprofile')),
            ],
            options={
                'verbose_name': 'Daily Attendance',
                'verbose_name_plural': 'Daily Attendance Records',
                'db_table': 'daily_attendance',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
