# Generated by Django 5.0.1 on 2025-12-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_schoolsettings_teacherprofile_dailyattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='school_id',
            field=models.CharField(blank=True, help_text='Official School ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='school_logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logo/'),
        ),
    ]
